name: CI for ASW2122

on:
  push:
    branches: [ master ]

jobs:
  unit-test-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: codecov/codecov-action@v2
  unit-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm test
    - uses: codecov/codecov-action@v2
  #e2e-tests: ðŸ‘€ðŸ‘€ðŸ‘€
    #needs: [unit-test-webapp, unit-test-restapi]
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- uses: actions/setup-node@v2
    #  with:
    #    node-version: 16
    #- run: npm --prefix webapp install
    #- run: npm --prefix restapi install
    #- run: npm --prefix webapp run build
    #- run: npm --prefix webapp run test:e2e
  deploy-webapp:
    needs: [unit-test-webapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dede-webapp-jesus"
          heroku_email: "jesus.ag00@gmail.com"
          usedocker: true
          dontuseforce : 1
          appdir: "webapp"
          docker_build_args: |
            API_URI
        env:
          API_URI: "https://dede-restapi-jesus.herokuapp.com/api"
  deploy-restapi:
    needs: [unit-test-restapi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dede-restapi-jesus"
          heroku_email: "jesus.ag00@gmail.com"
          usedocker: true
          appdir: "restapi"
          docker_build_args: |
            DEDE
        env:
          DEDE: ${{secrets.MONGO_URI}}
